const frases = {
    inspiracion: [
        "MAESTRA, TU DEDICACIÓN ES EL CIMIENTO SOBRE EL QUE TUS ALUMNOS CONSTRUYEN SUS SUEÑOS.",
        "ENSEÑAR ES TU ARTE Y EL FUTURO ES TU LIENZO; GRACIAS POR PINTARLO CON TANTO AMOR.",
        "TU PASIÓN ES EL FARO QUE GUÍA A TUS ALUMNOS INCLUSO EN SUS DÍAS MÁS NUBLADOS.",
        "NO SOLO TRANSMITES SABER, MAESTRA; AYUDAS A CADA NIÑO A ENCONTRAR SU PROPIA VOZ.",
        "LA HUELLA QUE DEJAS EN TUS ESTUDIANTES ES UNA MARCA DE ESPERANZA PARA EL MUNDO.",
        "TU PACIENCIA ES EL LENGUAJE MÁS DULCE QUE CONOCE EL CORAZÓN DE TUS ALUMNOS.",
        "MÁS QUE DATOS, LES REGALAS PERSPECTIVA. GRACIAS POR SER LA GUÍA QUE ELLOS NECESITAN.",
        "CADA LECCIÓN QUE PREPARAS ES UNA SEMILLA QUE FLORECERÁ EN LOS LOGROS DE MAÑANA.",
        "TU VOCACIÓN TRANSFORMA VIDAS Y DIBUJA CAMINOS DONDE ANTES SOLO HABÍA DUDAS.",
        "EL MUNDO ES UN LUGAR MÁS BRILLANTE GRACIAS A LA LUZ QUE APORTAS EN TU AULA.",
        "TU ENTREGA DIARIA COMO MAESTRA ES EL MEJOR EJEMPLO DE VALENTÍA Y DULZURA.",
        "HAS ELEGIDO LA PROFESIÓN MÁS NOBLE: AYUDAR A OTROS A DESCUBRIR SU PROPIO POTENCIAL.",
        "GRACIAS POR CREER EN TUS ALUMNOS, MAESTRA, INCLUSO CUANDO ELLOS DUDAN DE SÍ MISMOS.",
        "TU SABIDURÍA ES EL TESORO MÁS GRANDE QUE TUS ALUMNOS LLEVARÁN CONSIGO SIEMPRE.",
        "SER MAESTRA ES EL ARTE MÁS BELLO: TOCAR EL FUTURO A TRAVÉS DE SUS MANOS.",
        "TU CONSTANCIA ES EL MOTOR QUE MANTIENE VIVA LA CURIOSIDAD EN TUS PEQUEÑOS.",
        "CADA PREGUNTA QUE RESPONDES CON PACIENCIA ES UNA OPORTUNIDAD DE CRECIMIENTO.",
        "ERES EL PUENTE SEGURO QUE UNE EL ESFUERZO DE HOY CON EL ÉXITO DE MAÑANA.",
        "TU CALIDEZ HACE QUE EL SALÓN DE CLASES SEA UN LUGAR MÁGICO PARA APRENDER.",
        "TU LABOR NO PASA DESAPERCIBIDA; ESTÁS CAMBIANDO EL MUNDO, UNA CLASE A LA VEZ."
    ],
    descanso: [
        "HASTA LA JARDINERA MÁS DILIGENTE NECESITA UNA PAUSA PARA QUE SUS FLORES SIGAN CRECIENDO.",
        "MAESTRA, TU VALOR NO DEPENDE DE TU PRODUCTIVIDAD; PERMÍTETE DESCANSAR Y SOLO SER.",
        "DEJA QUE EL MUNDO SIGA GIRANDO SIN TI POR UN RATO; TU ENERGÍA MERECE REPOSO.",
        "HAS DADO TANTO DE TI QUE HOY TE TOCA RECIBIR: UN MERECIDO RESPIRO Y PAZ.",
        "DESCONECTAR DEL AULA NO ES RENDIRSE, ES EL ACTO DE AUTOCUIDADO MÁS VALIENTE.",
        "TU LABOR ES INTENSA Y HERMOSA; HOY, EL MEJOR ACTO DE DOCENCIA ES TU DESCANSO.",
        "APAGA EL RUIDO DEL DÍA, SUELTA LA AGENDA Y QUÉDATE SOLO CON TU TRANQUILIDAD.",
        "PARA SEGUIR ILUMINANDO EL CAMINO DE OTROS, DEBES CUIDAR PRIMERO TU PROPIA LUZ.",
        "EL MUNDO PUEDE ESPERAR, MAESTRA; TU BIENESTAR ES LA PRIORIDAD QUE HOY TE DEBES.",
        "TÓMATE ESTE MOMENTO PARA RECARGAR TU ALMA; LO HAS GANADO CON CRECES.",
        "HOY NO TIENES QUE ENSEÑAR NADA, SOLO DISFRUTA DE TU PROPIO MOMENTO DE CALMA.",
        "CERRAR LOS OJOS Y RESPIRAR PROFUNDO ES EL MEJOR REGALO QUE TE PUEDES DAR HOY.",
        "NO TE SIENTAS CULPABLE POR PAUSAR; TU DESCANSO ES LA FUENTE DE TU PRÓXIMA IDEA.",
        "HAS TRABAJADO DURO, HOY TU ÚNICA TAREA ES CONSENTIRTE Y REPONER FUERZAS.",
        "LAS MAESTRAS MÁS BRILLANTES SON LAS QUE SABEN CUÁNDO ES TIEMPO DE REPOSAR.",
        "EL SILENCIO TAMBIÉN TE ENSEÑA COSAS QUE EL RUIDO DE LOS LIBROS NO PERMITE.",
        "SUELTA LAS PREOCUPACIONES EN LA PUERTA; HOY SOLO TIENE LUGAR TU DESCANSO.",
        "TU MENTE ES TU HERRAMIENTA MÁS VALIOSA, DALE LA CALMA QUE NECESITA PARA BRILLAR.",
        "HOY EL MEJOR LIBRO QUE PUEDES LEER ES AQUEL QUE TE BRINDA PAZ Y RELAJACIÓN.",
        "MAESTRA, TU DESCANSO ES EL EJEMPLO MÁS GRANDE QUE PUEDES DAR SOBRE EL AUTOCUIDADO."
    ]
};
function mostrarFrase(tipo) {
    confetti({ particleCount: 300, spread: 150, origin: { y: 0.6 } });

    const cajaFrases = document.getElementById('frase');
    const lista = frases[tipo];
    const aleatoria = lista[Math.floor(Math.random() * lista.length)];
    
    cajaFrases.style.opacity = 0;
    setTimeout(() => {
        cajaFrases.textContent = aleatoria;
        cajaFrases.style.opacity = 1;
    }, 300);
}

function reiniciarMensaje() {
    const cajaFrases = document.getElementById('frase');
    cajaFrases.style.opacity = 0;
    setTimeout(() => {
        cajaFrases.textContent = "¿CÓMO TE SIENTES HOY MISS?";
        cajaFrases.style.opacity = 1;
    }, 300);
}

// Lluvia de útiles
function crearLluvia() {
    const contenedor = document.getElementById('lluvia');
    const utiles = ['✏️', '📏', '📐', '✂️', '🖍️', '📖', '📝'];
    
    setInterval(() => {
        const util = document.createElement('div');
        util.classList.add('util');
        util.textContent = utiles[Math.floor(Math.random() * utiles.length)];
        util.style.fontSize = (Math.random() * 160 + 110) + 'px';
        util.style.left = Math.random() * 100 + 'vw';
        util.style.animationDuration = (Math.random() * 3 + 2) + 's';
        contenedor.appendChild(util);
        setTimeout(() => util.remove(), 5000);
    }, 300);
}

crearLluvia();