const frases = {
    inspiracion: [
        "MISS YEIMY, TU DEDICACIÓN ES EL CIMIENTO SOBRE EL QUE TUS ALUMNOS CONSTRUYEN SUS SUEÑOS.",
        "'LA EDUCACIÓN ES EL ARMA MÁS PODEROSA QUE PUEDES USAR PARA CAMBIAR EL MUNDO' (NELSON MANDELA). ASÍ LO HACES TÚ CADA DÍA.",
        "'EDUCAR LA MENTE SIN EDUCAR EL CORAZÓN NO ES EDUCACIÓN EN ABSOLUTO' (ARISTÓTELES). GRACIAS POR HACER AMBAS, MISS YEIMY.",
        "MISS YEIMY, TU LABOR ES SEMBRAR VERDAD: 'DAME LA LUZ QUE NECESITO PARA PODER VER LA REALIDAD' (ANÓNIMO).",
        "'EL OBJETO DE LA EDUCACIÓN ES FORMAR SERES APTOS PARA GOBERNARSE A SÍ MISMOS' (HERBERT SPENCER). ESTÁS CREANDO LÍDERES.",
        "'LO QUE ESCULPE A UN NIÑO NO SON LAS PALABRAS, SINO EL EJEMPLO DE QUIEN LE ENSEÑA' (ALBERT SCHWEITZER). ERES ESE EJEMPLO, MISS YEIMY.",
        "MISS YEIMY, SER MAESTRA ES EL ARTE MÁS BELLO: TOCAR EL FUTURO A TRAVÉS DE LAS MANOS DE TUS NIÑOS.",
        "'QUERER QUERERSE ES EL PRIMER PASO PARA PODER QUERER A OTROS' (ANÓNIMO). GRACIAS POR ENSEÑARLES A AMAR APRENDIENDO.",
        "'ENSEÑAR ES ESCRIBIR EN EL CORAZÓN DE UN NIÑO Y DEJAR HUELLAS PARA SIEMPRE' (ANÓNIMO).",
        "'EL MAESTRO SUPERIOR DEMUESTRA' (WILLIAM ARTHUR WARD). MISS YEIMY, TUS ACCIONES SON TU MEJOR LECCIÓN.",
        "LA HUELLA QUE DEJAS EN TUS ESTUDIANTES, MISS YEIMY, ES UNA MARCA DE ESPERANZA PARA EL MUNDO.",
        "TU PACIENCIA ES EL LENGUAJE MÁS DULCE QUE CONOCE EL CORAZÓN DE TUS ALUMNOS, MISS YEIMY.",
        "'UN NIÑO, UN PROFESOR, UN LIBRO Y UN LÁPIZ PUEDEN CAMBIAR EL MUNDO' (MALALA YOUSAFZAI). TÚ ERES ESA PROFESORA.",
        "CADA LECCIÓN QUE PREPARAS, MISS YEIMY, ES UNA SEMILLA QUE FLORECERÁ EN LOS LOGROS DE MAÑANA.",
        "TU VOCACIÓN TRANSFORMA VIDAS Y DIBUJA CAMINOS DONDE ANTES SOLO HABÍA DUDAS, MISS YEIMY.",
        "MISS YEIMY, EL MUNDO ES MÁS BRILLANTE GRACIAS A TI: 'LA LUZ ES LO ÚNICO QUE ILUMINA LA OSCURIDAD' (ANÓNIMO).",
        "'LA ENSEÑANZA QUE DEJA HUELLA NO ES LA QUE SE HACE DE CABEZA A CABEZA, SINO DE CORAZÓN A CORAZÓN' (HOWARD HENDRICKS).",
        "MISS YEIMY, HAS ELEGIDO LA PROFESIÓN MÁS NOBLE: AYUDAR A OTROS A DESCUBRIR SU POTENCIAL.",
        "GRACIAS POR CREER EN TUS ALUMNOS. 'LA CONFIANZA ES EL PRIMER SECRETO DEL ÉXITO' (RALPH WALDO EMERSON).",
        "TU SABIDURÍA, MISS YEIMY, ES EL TESORO MÁS GRANDE QUE TUS ALUMNOS LLEVARÁN CONSIGO.",
        "'DIME Y LO OLVIDO, ENSÉÑAME Y LO RECUERDO, INVOLÚCRAME Y LO APRENDO' (BENJAMIN FRANKLIN). ESO HACES EN TU AULA.",
        "MISS YEIMY, CADA PREGUNTA QUE RESPONDES CON PACIENCIA ES UNA OPORTUNIDAD DE CRECIMIENTO.",
        "ERES EL PUENTE SEGURO QUE UNE EL ESFUERZO DE HOY CON EL ÉXITO DE MAÑANA, MISS YEIMY.",
        "NO HAY MAYOR RIQUEZA QUE LA MENTE Y EL CORAZÓN QUE DECIDES CULTIVAR EN TUS ALUMNOS.",
        "'EL ARTE SUPREMO DEL MAESTRO ES DESPERTAR EL PLACER DE LA EXPRESIÓN' (ALBERT EINSTEIN). LO LOGRAS, MISS YEIMY.",
        "MISS YEIMY, TU VOCACIÓN ES UN REGALO: 'LA EDUCACIÓN NO LLENA UN CUBO, SINO QUE ENCIENDE UN FUEGO' (W.B. YEATS).",
        "TIENES EL DON ÚNICO DE CONVERTIR CUALQUIER LECCIÓN EN UNA AVENTURA, MISS YEIMY.",
        "GRACIAS POR SER LA MAESTRA QUE MARCARÁ UN ANTES Y UN DESPUÉS EN SUS VIDAS.",
        "'CADA ALUMNO ES UNA PROMESA DE FUTURO' (JOHANN HEINRICH PESTALOZZI). GRACIAS POR GUIARLOS.",
        "'LA VIDA ES CORTA Y EL TIEMPO ES ORO' (ANÓNIMO). GRACIAS POR INVERTIR EL TUYO EN TUS ALUMNOS, MISS YEIMY."
    ],
    descanso: [
        "MISS YEIMY, HASTA LA JARDINERA MÁS DILIGENTE NECESITA UNA PAUSA. 'EL DESCANSO ES PARTE DEL TRABAJO' (OVIDIO).",
        "MAESTRA, TU VALOR NO DEPENDE DE TU PRODUCTIVIDAD. 'MENOS ES MÁS' (LUDWIG MIES VAN DER ROHE).",
        "'A VECES EL PASO MÁS IMPORTANTE ES EL QUE DAS HACIA ATRÁS PARA TOMAR IMPULSO' (ANÓNIMO). DESCANSA, MISS YEIMY.",
        "'ES NECESARIO A VECES PENSAR EN LO QUE SIENTES' (ANÓNIMO). MISS YEIMY, DALE TIEMPO A TU PAZ.",
        "MISS YEIMY, DESCONECTAR DEL AULA ES EL ACTO DE AUTOCUIDADO MÁS VALIENTE.",
        "'LA FELICIDAD NO ES UN DESTINO, SINO UNA FORMA DE VIAJAR' (MARGARET LEE RUNBECK). DISFRUTA TU DESCANSO.",
        "PARA SEGUIR ILUMINANDO, CUIDA TU PROPIA LUZ. 'EL EQUILIBRIO ES LA CLAVE' (PITÁGORAS).",
        "'TODO LO QUE NECESITAS ES AMOR Y PAZ' (ANÓNIMO). HOY, DATE ESE REGALO, MISS YEIMY.",
        "NO TE SIENTAS CULPABLE POR PAUSAR. 'LA NATURALEZA NO TIENE PRISA Y TODO SE LOGRA' (LAO TSÉ).",
        "MAESTRA, TU DESCANSO ES EL MEJOR EJEMPLO DE AUTOCUIDADO PARA TUS ALUMNOS.",
        "'EL DESCANSO ES LA MEJOR MEDICINA PARA LA MENTE' (HIPÓCRATES). APROVÉCHALO, MISS YEIMY.",
        "HAS DADO TANTO, HOY RECIBE: 'QUIEN SABE DESCANSAR, SABE VIVIR' (ANÓNIMO).",
        "MISS YEIMY, TU LABOR ES INTENSA. 'NO SE PUEDE SER FUERTE SIN HABER SIDO DÉBIL' (ANÓNIMO).",
        "APAGA EL RUIDO DEL DÍA. 'LA TRANQUILIDAD ES EL MÁXIMO VALOR' (SÉNECA).",
        "EL MUNDO PUEDE ESPERAR, MISS YEIMY. 'TÓMATE TIEMPO PARA VIVIR' (RALPH WALDO EMERSON).",
        "RECARGA TU ALMA. 'EL ALMA NECESITA SILENCIO PARA CRECER' (THOMAS MERTON).",
        "DISFRUTA TU CALMA. 'LA PAZ COMIENZA CON UNA SONRISA' (MADRE TERESA DE CALCUTA).",
        "CERRAR LOS OJOS Y RESPIRAR ES UN REGALO: 'RESPIRA, ES SOLO UN MAL DÍA, NO UNA MALA VIDA' (ANÓNIMO).",
        "REPON FUERZAS. 'EL QUE NO PUEDE DESCANSAR, NO PUEDE CREAR' (ANÓNIMO).",
        "MISS YEIMY, LAS MAESTRAS MÁS BRILLANTES SABEN CUÁNDO ES TIEMPO DE REPOSAR.",
        "'EL SILENCIO TAMBIÉN TE ENSEÑA' (ANÓNIMO). DISFRÚTALO, MISS YEIMY.",
        "SUELTA LAS PREOCUPACIONES. 'NO CARGUES CON EL MUNDO, EL MUNDO TIENE SUS PROPIOS PESOS' (ANÓNIMO).",
        "DALE A TU MENTE CALMA. 'LA MENTE ES TODO, EN LO QUE PIENSAS TE CONVIERTES' (BUDA).",
        "MISS YEIMY, EL MEJOR LIBRO ES EL QUE TE DA PAZ ESTA TARDE.",
        "'LA AMABILIDAD ES UN LENGUAJE QUE LOS SORDOS PUEDEN OÍR Y LOS CIEGOS VER' (MARK TWAIN). SÉ AMABLE CONTIGO.",
        "UNA MAESTRA DESCANSADA ES UNA FUERZA DE LA NATURALEZA, MISS YEIMY.",
        "'SI NO HAY PAZ EN TU INTERIOR, NO LA BUSQUES EN EL EXTERIOR' (FRANCISCO DE ASÍS).",
        "'SOLO QUIERO QUE EL MUNDO SEPA QUE AQUÍ ESTOY' (ANÓNIMO), PERO HOY PRIMERO ESTOY BIEN CONMIGO.",
        "MISS YEIMY, TU CUERPO ES TU TEMPLO. 'CUIDA TU CUERPO, ES EL ÚNICO LUGAR QUE TIENES PARA VIVIR' (JIM ROHN).",
        "EL SOL SE PONE PARA SALIR CON MÁS FUERZA. 'DESPUÉS DE LA TORMENTA SIEMPRE VIENE LA CALMA' (CERVANTES)."
    ],
    motivacion: [
        "¡TÚ PUEDES CON ESTO Y MUCHO MÁS, MISS YEIMY!",
        "TU ENERGÍA ES IMPARABLE. 'LA ENERGÍA Y LA PERSISTENCIA CONQUISTAN TODAS LAS COSAS' (BENJAMIN FRANKLIN).",
        "'SI QUIERES CAMBIAR EL MUNDO, CÁMBIATE A TI MISMO' (ANÓNIMO). TÚ LO LOGRAS EN TU AULA, MISS YEIMY.",
        "'EL ÉXITO ES LA SUMA DE PEQUEÑOS ESFUERZOS REPETIDOS DÍA TRAS DÍA' (ROBERT COLLIER).",
        "ERES UNA FUERZA DE LA NATURALEZA. 'LA FUERZA VIENE DE UNA VOLUNTAD INDOMABLE' (MAHATMA GANDHI).",
        "'QUIEN NO LUCHA POR LO QUE QUIERE, NO MERECE LO QUE DESEA' (ANÓNIMO). ¡SIGUE LUCHANDO, MISS YEIMY!",
        "MISS YEIMY, TU DEDICACIÓN HOY ES EL ÉXITO DE MAÑANA.",
        "'NO IMPORTA LO LENTO QUE VAYAS MIENTRAS NO TE DETENGAS' (CONFUCIO). ¡NO TE DETENGAS, MISS YEIMY!",
        "TU PASIÓN POR ENSEÑAR ES INFECCIOSA, MISS YEIMY.",
        "TU VOCACIÓN ES UN MOTOR. 'CREER EN TI MISMO ES EL PRIMER PASO HACIA LA GLORIA' (ANÓNIMO).",
        "MISS YEIMY, ERES EL EJEMPLO DE QUE CON ESFUERZO TODO SE ALCANZA.",
        "CREE EN TI. 'EL LÍMITE ES SOLO TU IMAGINACIÓN' (NAPOLEON HILL).",
        "'EL MUNDO ES TUYO' (ANÓNIMO). ¡HAZLO TUYO EN CADA CLASE, MISS YEIMY!",
        "LA FUERZA NO VIENE DE LA CAPACIDAD FÍSICA. 'LA FUERZA VIENE DE UN ESPÍRITU INVENCIBLE' (VIKTOR FRANKL).",
        "CADA DÍA ES UNA OPORTUNIDAD. 'LA ESPERANZA ES LO ÚLTIMO QUE SE PIERDE' (ANÓNIMO).",
        "'EL ÚNICO LÍMITE PARA NUESTROS LOGROS SON NUESTRAS DUDAS' (FRANKLIN D. ROOSEVELT).",
        "MISS YEIMY, TU DEDICACIÓN ES EL COMBUSTIBLE DE TUS ALUMNOS.",
        "ERES UNA MAESTRA EXTRAORDINARIA. 'LA EXCELENCIA ES UN HÁBITO' (ARISTÓTELES).",
        "SIGUE CON LA CABEZA ALTA. 'TU PASADO NO DEFINE TU FUTURO' (ANÓNIMO).",
        "¡NO HAY OBSTÁCULO QUE TU VOCACIÓN NO PUEDA VENCER, MISS YEIMY!"
    ]
};
function mostrarFrase(tipo) {
    confetti({ particleCount: 150, spread: 70, origin: { y: 0.6 }, colors: ['#6a1b9a', '#0288d1', '#c6ff00'] });

    const cajaFrases = document.getElementById('frase');
    const lista = frases[tipo];
    const aleatoria = lista[Math.floor(Math.random() * lista.length)];

    cajaFrases.classList.add('animar-cambio');
    setTimeout(() => {
        cajaFrases.textContent = aleatoria;
        cajaFrases.classList.remove('animar-cambio');
    }, 300);
}

function reiniciarMensaje() {
    const cajaFrases = document.getElementById('frase');
    cajaFrases.style.opacity = 0;
    setTimeout(() => {
        cajaFrases.textContent = "¿CÓMO TE SIENTES HOY MISS YEIMY?";
        cajaFrases.style.opacity = 1;
    }, 300);
}

// Lluvia de útiles mejorada
function crearLluvia() {
    const contenedor = document.getElementById('lluvia');
    const utiles = ['✏️', '📏', '📐', '✂️', '🖍️', '📖', '📝'];
    setInterval(() => {
        const util = document.createElement('div');
        util.classList.add('util');
        util.textContent = utiles[Math.floor(Math.random() * utiles.length)];
        util.style.left = Math.random() * 100 + 'vw';
        util.style.animationDuration = '5s';
        contenedor.appendChild(util);
        setTimeout(() => util.remove(), 5000);
    }, 1000);
}

// Lluvia de útiles
function crearLluvia() {
    const contenedor = document.getElementById('lluvia');
    const utiles = ['✏️', '📏', '📐', '✂️', '🖍️', '📖', '📝', // Tus originales
    '🎒', '🏫', '🍎', '💻', '🎨', '📎', '📌', 
    '🔍', '🧬', '🔬', '🌍', '🧮', '🎓', '💡'
];
    
    setInterval(() => {
        const util = document.createElement('div');
        util.classList.add('util');
        util.textContent = utiles[Math.floor(Math.random() * utiles.length)];
        util.style.fontSize = (Math.random() * 130 + 90) + 'px';
        util.style.left = Math.random() * 100 + 'vw';
        util.style.animationDuration = (Math.random() * 5 + 3) + 's';
        contenedor.appendChild(util);
        setTimeout(() => util.remove(), 5000);
    }, 300);
}

crearLluvia();

if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('sw.js');
}

function saludarSegunHora() {
    const saludoElemento = document.getElementById('saludo');
    const hora = new Date().getHours();
    let mensaje = "¡Hola, Maestra Yeimy!"; // Por defecto

    if (hora >= 5 && hora < 12) {
        mensaje = "¡Buenos días, Miss Yeimy! ☀️";
    } else if (hora >= 12 && hora < 19) {
        mensaje = "¡Buenas tardes, Miss Yeimy! 🌷";
    } else {
        mensaje = "¡Buenas noches, Miss Yeimy! 🌙";
    }

    saludoElemento.textContent = mensaje;
}

// Llamar a la función apenas cargue la página
saludarSegunHora();











